from django.contrib import admin
from django.urls import path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Qauto (autogenerated)",
        default_version='v1',
        description="API for Qauto sample project",
        contact=openapi.Contact(email="support@test.ua"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
    authentication_classes=[],
)

# # Додайте кастомну обгортку для автоматичного додавання Bearer
# from functools import wraps
# from django.utils.decorators import method_decorator

# def add_bearer_prefix(view_func):
#     @wraps(view_func)
#     def wrapper(request, *args, **kwargs):
#         auth_header = request.META.get('HTTP_AUTHORIZATION', '')
#         if auth_header and not auth_header.startswith('Bearer '):
#             request.META['HTTP_AUTHORIZATION'] = f'Bearer {auth_header}'
#         return view_func(request, *args, **kwargs)
#     return wrapper


urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/auth/", include("users.urls_auth")),
    path("api/users/", include("users.urls")),
    path("api/cars/", include("cars.urls")),
    # Swagger/OpenAPI:
    path("swagger(<format>\.json|\.yaml)", schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path("swagger/", schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path("redoc/", schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]